### ISSUE TITLE
Routing error after 2.15.1

### ISSUE THREAD

**Issue by arkanoid87** [oscarfonts/docker-geoserver#23]
I get routing errors on multiple pages when serving geoserver behind proxy server as TLS terminator.

I solved the problem by downgrading version to 2.15.1

Afaics 2.15.4 and 2.16.2 are affected.

**Comment by Zalitoar** [comment]
Hi @arkanoid87 maybe you're going into the same issue I had from some time ago. 

The issue appeared while browsing to other pages in the layers preview page, tabs within layers configuration and other similar. The app doesn't do anything, it just keep on the opened page.

I solved it by adding the GEOSERVER_CSRF_WHITELIST environment variable with the domain where is GeoServer as value (it works with an IP too). This is caused by CSRF Protection mechanism.

You can also disable CSRF with GEOSERVER_CSRF_DISABLED=TRUE.

I found it in the docs: https://docs.geoserver.org/stable/en/user/security/webadmin/csrf.html

Hope this would be useful.

**Comment by victorzinho** [comment]
Thanks @Zalitoar for the support!
Closing the ticket since it's quite old and seems resolved. Feel free to reopen if the issue is not resolved.
