### ISSUE TITLE
Out of Memory Errors

### ISSUE THREAD

**Issue by TimothyKebbel** [oscarfonts/docker-geoserver#30]
I am running into an issue where the memory usage of my container steadily increases until I receive an OOM error which forces a reset of the container. Each wms request seems to increase the ram used in my container but the ram is never released. I've tried modifying the heap size and garbage collection of the CATALINA_OPTS variable but the results are always the same. Is there additional configuration for the JVM that I am missing, or is this a docker issue?

**Comment by t-book** [comment]
@TimothyKebbel Did you find a solution here?

**Comment by TimothyKebbel** [comment]
@t-book 
I haven't been able to determine the cause of the memory leak. Adding more RAM to the container has helped stability but hasn't addressed the actual problem. The garbage collector seemingly runs however, any memory released gets immediately consumed again.
![Untitled](https://user-images.githubusercontent.com/28766792/165101120-3df611c4-d3df-4907-a8fe-e1a3023fc9c3.png)

**Comment by oscarfonts** [comment]
We've had multiple instances of this image in production running for years, without this OOM issue being reported.

My guess is that this can a memory leak issue in geoserver, depending on your specific configuration, and not related to docker itself.

There's little we can do about it with this information. Is there a way this behaviour can be reproduced, in order to test it? Have you tried with other geoserver images/environment setup and found differences?
