### ISSUE TITLE
chown problematic with heavy gwc folder

### ISSUE THREAD

**Issue by t-book** [oscarfonts/docker-geoserver#31]
Hi @oscarfonts,

thanks for this great composition. I'm using your stack to serve OSM tiles. Strangely, geoserver suddenly did not up anymore. This is what happened.

The GWC tiles folder weigh around 600 GB. After some debugging, I've found that 

https://github.com/oscarfonts/docker-geoserver/blob/1b7cd6c97f74555e0faf807cecbb158a579d372b/2.20.2/start.sh#L16

is taking several hours to finish. Which slows down the startup immensely.

**Things that come to my mind to mitigate the issue**

1. as an easy solution, the README could warn users, about this behavior. Doing so they hopefully will not try to find problems that are not there
2. A console message could inform the user that the process is running 
3. I'm currently just ignoring the gwc folder `chown -R tomcat:tomcat $(ls ${GEOSERVER_DATA_DIR} -I gwc)`. Not perfect but works in my case

**Comment by guydriesen** [comment]
Hi,

We had exactly the same problem a couple of weeks ago...
Since we also make use of the CUSTOM_UID / CUSTOM_GID feature, the whole datadir got chowned 3 times.
One of our geoserver containers took literally 45 to 60 minutes to start, just because chowing millions of files takes it's time. With the changes from the PR #32, it only takes a couple of minutes to get it running.

Br,
Guy.
