### ISSUE TITLE
Workspace

### ISSUE THREAD

**Issue by bambryan** [oscarfonts/docker-geoserver#33]
I loaded your image into Kubernetes and I have set my presistant volume to the correct directory where the image writes a default configs but then I goto create a workspace and it throws an error along with many other pages under the system status screen.

HTTP Status 400 – Bad Request

Type Status Report

Message Origin does not correspond to request

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

I have a config from a current production server but I don't want to waste time loading it if I can't test with a default setup.

**Comment by victorzinho** [comment]
Hello @bambryan 

Kubernetes is huge, "loaded your image into Kubernetes" doesn't give us much information about your setup, how you query geoserver or what might be failing. In the past I had similar issues performing certain operations in the web admin of this image deployed to k8s pods with an ingress in front handling everything related to the domain, ssl, load balancing, etc. A solution was to use the [proxy](https://docs.geoserver.org/stable/en/user/configuration/globalsettings.html#proxy-base-url) and [CSRF](https://docs.geoserver.org/main/en/user/security/webadmin/csrf.html) configurations, like [here](https://gis.stackexchange.com/questions/385106/unable-to-add-layer-to-geoserver-origin-does-not-correspond-to-request). Another solution was to skip the ingress and connect to the pod directly with `kubectl port-forward`; clearly worse but it might work in certain scenarios where the person editing the catalog knows how to use kubectl and doesn't have to do it often.

I'm not sure if any of this is of any use to your problem, but it seems to me the problem is more related to how to generally put geoserver in kubernetes rather than problems with how this image is built. You might have more luck asking this to a broader audience in stackoverflow or the geoserver mailing list.

**Comment by victorzinho** [comment]
Closing the ticket since it's quite old and seems outside the scope of the docker image itself. Feel free to reopen if the issue is not resolved.
