### ISSUE TITLE
Allow custom fonts injection

### ISSUE THREAD

**Issue by sharkAndshark** [oscarfonts/docker-geoserver#35]
Install custom fonts for labeling when it started
* Add custom fonts  volume
* Generate fonts cache when it started

For now I make it like this :
```shell
docker run ...... -v /custom_fonts_dir:/usr/share/fonts/custom ....  oscarfonts/geoserver:2.23.1
docker exec -it ....
cd /usr/share/fonts/
mkfontscale
....
```

It would be convenient if this image could automatically generate the font cache

**Comment by victorzinho** [comment]
Hello @sharkAndshark 
We aim to keep this image as simple as possible to be able to maintain it successfully. The custom fonts seems like a specific use case that can be easily solved by extending this image in another Dockerfile with `FROM oscarfonts/geoserver` or with the instructions you wrote.

However, if I'm wrong and this is not such a specific use case and more people need it we're happy to receive pull requests :)

**Comment by sharkAndshark** [comment]
Guess it's useful for Japanese/Chinese/Arabic etc users.

**Comment by victorzinho** [comment]
To be honest I'm not very proficient with fonts and different alphabets. But I think that problem is solved with encoding rather  than fonts? I have successfully done that in the past (plain java, outside of geoserver) to generate pdf files in japanese using shift-jis encoding and the same font as for english (some serif if I remember correctly). It seems it was the case here as well (someone displaying arabic in qgis/geoserver using arial): https://stackoverflow.com/questions/56323836/arabic-labels-do-not-display-correctly-in-geoserver

In fact ideally you wouldn't need a specific encoding and unicode should cover most of the cases, independently of the font: https://en.wikipedia.org/wiki/Japanese_language_and_computers#Character_encodings

**Comment by sharkAndshark** [comment]
@victorzinho Thx!! Interesting.I need a little bit research on it.

**Comment by sharkAndshark** [comment]
Hi @victorzinho  Seems that the JRE or Windows/Linux will try another font when you are trying to render Japanese/English characters with English fonts.  There is an font rendering order.. I would post some official document once I find.
