### ISSUE TITLE
Could not create the Java Virtual Machine

### ISSUE THREAD

**Issue by spawn-guy** [oscarfonts/docker-geoserver#42]
Hello, All. 

in the past few weeks we started noticing some weird JVM problems with `oscarfonts/geoserver:latest`.
i'm running this thing on AWS ElasticBeanstalk `Docker running on 64bit Amazon Linux 2/3.5.9` 

and the environments started to be marked as `Severe` and nothing is working (duh)

i pulled the logs from the instances and they all say
```
stdout: , stderr: NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

rolling back to  `oscarfonts/geoserver:2.22.5` fixed the problem

can someone have a look at this? can i help in some way?

**Comment by oscarfonts** [comment]
Cannot reproduce this error. Just ran a clean `docker run -p 8080:8080 oscarfonts/geoserver:latest` and it's working.

The 'UseConcMarkSweepGC' VM option is no longer supported since we moved to java 17 (geoserver images 2.23.1 and above), so it was removed from the Dockerfile (see https://github.com/oscarfonts/docker-geoserver/commit/4269e48d79aebca55456ef20a394ba5cc25ef5b7).

Check whether you're running an old cached image or adding the 'UseConcMarkSweepGC' somewhere else.

By the way, for production environments, I'd recommend you to use an explicit version tag instead of "latest".

**Comment by spawn-guy** [comment]
@oscarfonts thank you for reminder to lock production version.

However, i can not agree with the closure of this ticket.

just now i tried locking to versions `2.24.1` and `2.23.3` - both failed to start with the same error `Unrecognized VM option 'UseConcMarkSweepGC'`
on version `2.22.5` - it works as expected.

the linux i am running is `64bit Amazon Linux 2` it is centOS-forked (as i remember). also amazon has their own `coretto` which is their version of JAVA VM.

i am thinking there is some incompatibility between `tomcat:9-jre17` and this deployment setup.

Shall we investigate a bit more?

**Comment by spawn-guy** [comment]
so, tomcat ppl also don't set this setting anywhere 🤣
